### ISSUE TITLE
getting all defined attributes in a XExtension will throw an error

### ISSUE THREAD

**Issue by almarro1** [opyenxes/OpyenXes#8]
* OpyenXes version: 0.1.6
* Python version: 3.6.3
* Operating System: macos 10.13.1

### Description
I'm parsing a extension from a log, the extension is standard so the XExtensionManager can find it, but when invoking ```extension.get_defined_attributes()``` throws an error in line 64
 
The error trace is as follows:

```
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/opyenxes/extension/XExtension.py", line 64, in get_defined_attributes
    self.__all_attributes.add(self.__log_attributes)
TypeError: unhashable type: 'set'
```

A possible solution is to cast each individual component to a list, concatenate them and then create the set. Example:

```
self.__all_attributes = set(
                list(self.__log_attributes) +
                list(self.__trace_attributes) +
                list(self.__event_attributes) +
                list(self.__meta_attributes))
```

**Comment by wailamjonathanlee** [comment]
Hey thanks for the bug report. Seems to make sense, since ```self.__log_attributes``` is a set and that is not hashable. Will certainly consider your proposed solution after verification.
